### ISSUE TITLE
Исправить ошибку при записи в файл и добавить тесты

### ISSUE THREAD

**Issue by Kasiwadzaki** [yellowblacksnek/java0602#1]
Привет!  
Меня зовут Вадим, я разработчик компании BaltInfoCom. Я провел ревью твоего кода и есть пара моментов, которые я хотел бы чтобы ты исправил:  
 - Нужно убрать все System.exit и заменить их на выброс ошибки, которая завершит программу, при этом ошибки должны быть с понятным пользователю текстом, в случае первого System.exit это не критично, но в случае IOException хотелось бы чтобы был стектрейс ошибки. Так же лучше использовать блок else, в случае с первым if, тогда не будет необходимоти в System.exit
 - Нужно покрыть тестами твой код, добавь пару unit тестов для логики и один интеграционный на небольшой файл
 - И при выполнении файла возникла ошибка, ее необходимо поправить (Файл лежит по ссылке https://github.com/PeacockTeam/new-job/releases/tag/v1.0, называется lng-big.7z )
   ```
   Exception in thread "main" java.lang.StringIndexOutOfBoundsException: index -1, length 0
	at java.base/java.lang.String.checkIndex(String.java:3715)
	at java.base/java.lang.AbstractStringBuilder.deleteCharAt(AbstractStringBuilder.java:976)
	at java.base/java.lang.StringBuilder.deleteCharAt(StringBuilder.java:292)
	at org.example.Task.printGroups(Task.java:92)
	at org.example.Main.main(Main.java:33)
   ```

**Comment by Kasiwadzaki** [comment]
@yellowblacksnek Код и тесты в целом в порядке, но насчет ошибок, я имел ввиду было бы неплохо использовать ключевое слово throw, и заменить ими System.out выводы в блоках catch

**Comment by yellowblacksnek** [comment]
Теперь в catch блоках кидаются новые исключения с понятным сообщением и стектрейсом исходного. Если нужно, можно и unchecked исключение кидать, чтобы избавиться от окраски методов в throws.
Могу узнать, почему рекомендуешь избегать вывода в catch блоках?

**Comment by Kasiwadzaki** [comment]
@yellowblacksnek Обычно в проде мы используем логирование в файлы, любой вывод в консоль никак не сохраняется у клиента, для локальных задач sout может и подходит, но для больших проектов это моветон. Поэтому лучше сразу отбрасывать такой код.  В случаях когда ты просто выводишь на экран информацию, в данной задаче позволительно, но в случае с ошибками, я хотел увидеть как ты их обрабатываешь.
Запусти вот этот файл https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z и напиши какой ответ у тебя получился

**Comment by yellowblacksnek** [comment]
Спасибо за разъяснение! Ответ получился 105036.
